// <auto-generated />
using System;
using MagicSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicSystem.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MagicSystemContext))]
    partial class MagicSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MagicSystem")
                .HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Toolbox.Infrastructure.AuditTrail+Entry", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraContext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.HasIndex("CorrelationIdentifier");

                    b.ToTable("AuditedEvents", "MagicSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
